service: binary-express
plugins:
  - serverless-apigw-binary
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" } ] ]  }

custom:
  apigwBinary:
    types:
      - '*/*'
      -
functions:
  api:
    handler: lambda.express
    environment:
      AWS_API_KEY: #your key
      AWS_API_SECRET: #your secret
      AWS_BUCKET: # bucket name 
      IMAGE_WIDTH: 400 #image size
      IMAGE_HEIGHT: 225 #image size
    events:
      - http: ANY {proxy+}
      - http: ANY /
